# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.20

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/mihai/g4work/siddharta_bck

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/mihai/g4work/siddharta_bck

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/mihai/g4work/siddharta_bck/CMakeFiles /home/mihai/g4work/siddharta_bck//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/mihai/g4work/siddharta_bck/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named sidd_mc

# Build rule for target.
sidd_mc: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 sidd_mc
.PHONY : sidd_mc

# fast build rule for target.
sidd_mc/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sidd_mc.dir/build.make CMakeFiles/sidd_mc.dir/build
.PHONY : sidd_mc/fast

Siddharta.o: Siddharta.cpp.o
.PHONY : Siddharta.o

# target to build an object file
Siddharta.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sidd_mc.dir/build.make CMakeFiles/sidd_mc.dir/Siddharta.cpp.o
.PHONY : Siddharta.cpp.o

Siddharta.i: Siddharta.cpp.i
.PHONY : Siddharta.i

# target to preprocess a source file
Siddharta.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sidd_mc.dir/build.make CMakeFiles/sidd_mc.dir/Siddharta.cpp.i
.PHONY : Siddharta.cpp.i

Siddharta.s: Siddharta.cpp.s
.PHONY : Siddharta.s

# target to generate assembly for a file
Siddharta.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sidd_mc.dir/build.make CMakeFiles/sidd_mc.dir/Siddharta.cpp.s
.PHONY : Siddharta.cpp.s

src/G4KaonMinusAbsorptionAtRest.o: src/G4KaonMinusAbsorptionAtRest.cpp.o
.PHONY : src/G4KaonMinusAbsorptionAtRest.o

# target to build an object file
src/G4KaonMinusAbsorptionAtRest.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sidd_mc.dir/build.make CMakeFiles/sidd_mc.dir/src/G4KaonMinusAbsorptionAtRest.cpp.o
.PHONY : src/G4KaonMinusAbsorptionAtRest.cpp.o

src/G4KaonMinusAbsorptionAtRest.i: src/G4KaonMinusAbsorptionAtRest.cpp.i
.PHONY : src/G4KaonMinusAbsorptionAtRest.i

# target to preprocess a source file
src/G4KaonMinusAbsorptionAtRest.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sidd_mc.dir/build.make CMakeFiles/sidd_mc.dir/src/G4KaonMinusAbsorptionAtRest.cpp.i
.PHONY : src/G4KaonMinusAbsorptionAtRest.cpp.i

src/G4KaonMinusAbsorptionAtRest.s: src/G4KaonMinusAbsorptionAtRest.cpp.s
.PHONY : src/G4KaonMinusAbsorptionAtRest.s

# target to generate assembly for a file
src/G4KaonMinusAbsorptionAtRest.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sidd_mc.dir/build.make CMakeFiles/sidd_mc.dir/src/G4KaonMinusAbsorptionAtRest.cpp.s
.PHONY : src/G4KaonMinusAbsorptionAtRest.cpp.s

src/G4ShortLivedConstructor.o: src/G4ShortLivedConstructor.cpp.o
.PHONY : src/G4ShortLivedConstructor.o

# target to build an object file
src/G4ShortLivedConstructor.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sidd_mc.dir/build.make CMakeFiles/sidd_mc.dir/src/G4ShortLivedConstructor.cpp.o
.PHONY : src/G4ShortLivedConstructor.cpp.o

src/G4ShortLivedConstructor.i: src/G4ShortLivedConstructor.cpp.i
.PHONY : src/G4ShortLivedConstructor.i

# target to preprocess a source file
src/G4ShortLivedConstructor.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sidd_mc.dir/build.make CMakeFiles/sidd_mc.dir/src/G4ShortLivedConstructor.cpp.i
.PHONY : src/G4ShortLivedConstructor.cpp.i

src/G4ShortLivedConstructor.s: src/G4ShortLivedConstructor.cpp.s
.PHONY : src/G4ShortLivedConstructor.s

# target to generate assembly for a file
src/G4ShortLivedConstructor.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sidd_mc.dir/build.make CMakeFiles/sidd_mc.dir/src/G4ShortLivedConstructor.cpp.s
.PHONY : src/G4ShortLivedConstructor.cpp.s

src/PhiMassFunction.o: src/PhiMassFunction.cpp.o
.PHONY : src/PhiMassFunction.o

# target to build an object file
src/PhiMassFunction.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sidd_mc.dir/build.make CMakeFiles/sidd_mc.dir/src/PhiMassFunction.cpp.o
.PHONY : src/PhiMassFunction.cpp.o

src/PhiMassFunction.i: src/PhiMassFunction.cpp.i
.PHONY : src/PhiMassFunction.i

# target to preprocess a source file
src/PhiMassFunction.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sidd_mc.dir/build.make CMakeFiles/sidd_mc.dir/src/PhiMassFunction.cpp.i
.PHONY : src/PhiMassFunction.cpp.i

src/PhiMassFunction.s: src/PhiMassFunction.cpp.s
.PHONY : src/PhiMassFunction.s

# target to generate assembly for a file
src/PhiMassFunction.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sidd_mc.dir/build.make CMakeFiles/sidd_mc.dir/src/PhiMassFunction.cpp.s
.PHONY : src/PhiMassFunction.cpp.s

src/SiddhartaAnalysisManager.o: src/SiddhartaAnalysisManager.cpp.o
.PHONY : src/SiddhartaAnalysisManager.o

# target to build an object file
src/SiddhartaAnalysisManager.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sidd_mc.dir/build.make CMakeFiles/sidd_mc.dir/src/SiddhartaAnalysisManager.cpp.o
.PHONY : src/SiddhartaAnalysisManager.cpp.o

src/SiddhartaAnalysisManager.i: src/SiddhartaAnalysisManager.cpp.i
.PHONY : src/SiddhartaAnalysisManager.i

# target to preprocess a source file
src/SiddhartaAnalysisManager.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sidd_mc.dir/build.make CMakeFiles/sidd_mc.dir/src/SiddhartaAnalysisManager.cpp.i
.PHONY : src/SiddhartaAnalysisManager.cpp.i

src/SiddhartaAnalysisManager.s: src/SiddhartaAnalysisManager.cpp.s
.PHONY : src/SiddhartaAnalysisManager.s

# target to generate assembly for a file
src/SiddhartaAnalysisManager.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sidd_mc.dir/build.make CMakeFiles/sidd_mc.dir/src/SiddhartaAnalysisManager.cpp.s
.PHONY : src/SiddhartaAnalysisManager.cpp.s

src/SiddhartaAnti1SD.o: src/SiddhartaAnti1SD.cpp.o
.PHONY : src/SiddhartaAnti1SD.o

# target to build an object file
src/SiddhartaAnti1SD.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sidd_mc.dir/build.make CMakeFiles/sidd_mc.dir/src/SiddhartaAnti1SD.cpp.o
.PHONY : src/SiddhartaAnti1SD.cpp.o

src/SiddhartaAnti1SD.i: src/SiddhartaAnti1SD.cpp.i
.PHONY : src/SiddhartaAnti1SD.i

# target to preprocess a source file
src/SiddhartaAnti1SD.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sidd_mc.dir/build.make CMakeFiles/sidd_mc.dir/src/SiddhartaAnti1SD.cpp.i
.PHONY : src/SiddhartaAnti1SD.cpp.i

src/SiddhartaAnti1SD.s: src/SiddhartaAnti1SD.cpp.s
.PHONY : src/SiddhartaAnti1SD.s

# target to generate assembly for a file
src/SiddhartaAnti1SD.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sidd_mc.dir/build.make CMakeFiles/sidd_mc.dir/src/SiddhartaAnti1SD.cpp.s
.PHONY : src/SiddhartaAnti1SD.cpp.s

src/SiddhartaAnti2SD.o: src/SiddhartaAnti2SD.cpp.o
.PHONY : src/SiddhartaAnti2SD.o

# target to build an object file
src/SiddhartaAnti2SD.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sidd_mc.dir/build.make CMakeFiles/sidd_mc.dir/src/SiddhartaAnti2SD.cpp.o
.PHONY : src/SiddhartaAnti2SD.cpp.o

src/SiddhartaAnti2SD.i: src/SiddhartaAnti2SD.cpp.i
.PHONY : src/SiddhartaAnti2SD.i

# target to preprocess a source file
src/SiddhartaAnti2SD.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sidd_mc.dir/build.make CMakeFiles/sidd_mc.dir/src/SiddhartaAnti2SD.cpp.i
.PHONY : src/SiddhartaAnti2SD.cpp.i

src/SiddhartaAnti2SD.s: src/SiddhartaAnti2SD.cpp.s
.PHONY : src/SiddhartaAnti2SD.s

# target to generate assembly for a file
src/SiddhartaAnti2SD.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sidd_mc.dir/build.make CMakeFiles/sidd_mc.dir/src/SiddhartaAnti2SD.cpp.s
.PHONY : src/SiddhartaAnti2SD.cpp.s

src/SiddhartaAnti3SD.o: src/SiddhartaAnti3SD.cpp.o
.PHONY : src/SiddhartaAnti3SD.o

# target to build an object file
src/SiddhartaAnti3SD.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sidd_mc.dir/build.make CMakeFiles/sidd_mc.dir/src/SiddhartaAnti3SD.cpp.o
.PHONY : src/SiddhartaAnti3SD.cpp.o

src/SiddhartaAnti3SD.i: src/SiddhartaAnti3SD.cpp.i
.PHONY : src/SiddhartaAnti3SD.i

# target to preprocess a source file
src/SiddhartaAnti3SD.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sidd_mc.dir/build.make CMakeFiles/sidd_mc.dir/src/SiddhartaAnti3SD.cpp.i
.PHONY : src/SiddhartaAnti3SD.cpp.i

src/SiddhartaAnti3SD.s: src/SiddhartaAnti3SD.cpp.s
.PHONY : src/SiddhartaAnti3SD.s

# target to generate assembly for a file
src/SiddhartaAnti3SD.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sidd_mc.dir/build.make CMakeFiles/sidd_mc.dir/src/SiddhartaAnti3SD.cpp.s
.PHONY : src/SiddhartaAnti3SD.cpp.s

src/SiddhartaAnti4SD.o: src/SiddhartaAnti4SD.cpp.o
.PHONY : src/SiddhartaAnti4SD.o

# target to build an object file
src/SiddhartaAnti4SD.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sidd_mc.dir/build.make CMakeFiles/sidd_mc.dir/src/SiddhartaAnti4SD.cpp.o
.PHONY : src/SiddhartaAnti4SD.cpp.o

src/SiddhartaAnti4SD.i: src/SiddhartaAnti4SD.cpp.i
.PHONY : src/SiddhartaAnti4SD.i

# target to preprocess a source file
src/SiddhartaAnti4SD.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sidd_mc.dir/build.make CMakeFiles/sidd_mc.dir/src/SiddhartaAnti4SD.cpp.i
.PHONY : src/SiddhartaAnti4SD.cpp.i

src/SiddhartaAnti4SD.s: src/SiddhartaAnti4SD.cpp.s
.PHONY : src/SiddhartaAnti4SD.s

# target to generate assembly for a file
src/SiddhartaAnti4SD.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sidd_mc.dir/build.make CMakeFiles/sidd_mc.dir/src/SiddhartaAnti4SD.cpp.s
.PHONY : src/SiddhartaAnti4SD.cpp.s

src/SiddhartaAnti5SD.o: src/SiddhartaAnti5SD.cpp.o
.PHONY : src/SiddhartaAnti5SD.o

# target to build an object file
src/SiddhartaAnti5SD.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sidd_mc.dir/build.make CMakeFiles/sidd_mc.dir/src/SiddhartaAnti5SD.cpp.o
.PHONY : src/SiddhartaAnti5SD.cpp.o

src/SiddhartaAnti5SD.i: src/SiddhartaAnti5SD.cpp.i
.PHONY : src/SiddhartaAnti5SD.i

# target to preprocess a source file
src/SiddhartaAnti5SD.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sidd_mc.dir/build.make CMakeFiles/sidd_mc.dir/src/SiddhartaAnti5SD.cpp.i
.PHONY : src/SiddhartaAnti5SD.cpp.i

src/SiddhartaAnti5SD.s: src/SiddhartaAnti5SD.cpp.s
.PHONY : src/SiddhartaAnti5SD.s

# target to generate assembly for a file
src/SiddhartaAnti5SD.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sidd_mc.dir/build.make CMakeFiles/sidd_mc.dir/src/SiddhartaAnti5SD.cpp.s
.PHONY : src/SiddhartaAnti5SD.cpp.s

src/SiddhartaCard.o: src/SiddhartaCard.cpp.o
.PHONY : src/SiddhartaCard.o

# target to build an object file
src/SiddhartaCard.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sidd_mc.dir/build.make CMakeFiles/sidd_mc.dir/src/SiddhartaCard.cpp.o
.PHONY : src/SiddhartaCard.cpp.o

src/SiddhartaCard.i: src/SiddhartaCard.cpp.i
.PHONY : src/SiddhartaCard.i

# target to preprocess a source file
src/SiddhartaCard.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sidd_mc.dir/build.make CMakeFiles/sidd_mc.dir/src/SiddhartaCard.cpp.i
.PHONY : src/SiddhartaCard.cpp.i

src/SiddhartaCard.s: src/SiddhartaCard.cpp.s
.PHONY : src/SiddhartaCard.s

# target to generate assembly for a file
src/SiddhartaCard.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sidd_mc.dir/build.make CMakeFiles/sidd_mc.dir/src/SiddhartaCard.cpp.s
.PHONY : src/SiddhartaCard.cpp.s

src/SiddhartaDetectorConstruction.o: src/SiddhartaDetectorConstruction.cpp.o
.PHONY : src/SiddhartaDetectorConstruction.o

# target to build an object file
src/SiddhartaDetectorConstruction.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sidd_mc.dir/build.make CMakeFiles/sidd_mc.dir/src/SiddhartaDetectorConstruction.cpp.o
.PHONY : src/SiddhartaDetectorConstruction.cpp.o

src/SiddhartaDetectorConstruction.i: src/SiddhartaDetectorConstruction.cpp.i
.PHONY : src/SiddhartaDetectorConstruction.i

# target to preprocess a source file
src/SiddhartaDetectorConstruction.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sidd_mc.dir/build.make CMakeFiles/sidd_mc.dir/src/SiddhartaDetectorConstruction.cpp.i
.PHONY : src/SiddhartaDetectorConstruction.cpp.i

src/SiddhartaDetectorConstruction.s: src/SiddhartaDetectorConstruction.cpp.s
.PHONY : src/SiddhartaDetectorConstruction.s

# target to generate assembly for a file
src/SiddhartaDetectorConstruction.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sidd_mc.dir/build.make CMakeFiles/sidd_mc.dir/src/SiddhartaDetectorConstruction.cpp.s
.PHONY : src/SiddhartaDetectorConstruction.cpp.s

src/SiddhartaDetectorMessenger.o: src/SiddhartaDetectorMessenger.cpp.o
.PHONY : src/SiddhartaDetectorMessenger.o

# target to build an object file
src/SiddhartaDetectorMessenger.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sidd_mc.dir/build.make CMakeFiles/sidd_mc.dir/src/SiddhartaDetectorMessenger.cpp.o
.PHONY : src/SiddhartaDetectorMessenger.cpp.o

src/SiddhartaDetectorMessenger.i: src/SiddhartaDetectorMessenger.cpp.i
.PHONY : src/SiddhartaDetectorMessenger.i

# target to preprocess a source file
src/SiddhartaDetectorMessenger.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sidd_mc.dir/build.make CMakeFiles/sidd_mc.dir/src/SiddhartaDetectorMessenger.cpp.i
.PHONY : src/SiddhartaDetectorMessenger.cpp.i

src/SiddhartaDetectorMessenger.s: src/SiddhartaDetectorMessenger.cpp.s
.PHONY : src/SiddhartaDetectorMessenger.s

# target to generate assembly for a file
src/SiddhartaDetectorMessenger.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sidd_mc.dir/build.make CMakeFiles/sidd_mc.dir/src/SiddhartaDetectorMessenger.cpp.s
.PHONY : src/SiddhartaDetectorMessenger.cpp.s

src/SiddhartaEnergyDeposition.o: src/SiddhartaEnergyDeposition.cpp.o
.PHONY : src/SiddhartaEnergyDeposition.o

# target to build an object file
src/SiddhartaEnergyDeposition.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sidd_mc.dir/build.make CMakeFiles/sidd_mc.dir/src/SiddhartaEnergyDeposition.cpp.o
.PHONY : src/SiddhartaEnergyDeposition.cpp.o

src/SiddhartaEnergyDeposition.i: src/SiddhartaEnergyDeposition.cpp.i
.PHONY : src/SiddhartaEnergyDeposition.i

# target to preprocess a source file
src/SiddhartaEnergyDeposition.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sidd_mc.dir/build.make CMakeFiles/sidd_mc.dir/src/SiddhartaEnergyDeposition.cpp.i
.PHONY : src/SiddhartaEnergyDeposition.cpp.i

src/SiddhartaEnergyDeposition.s: src/SiddhartaEnergyDeposition.cpp.s
.PHONY : src/SiddhartaEnergyDeposition.s

# target to generate assembly for a file
src/SiddhartaEnergyDeposition.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sidd_mc.dir/build.make CMakeFiles/sidd_mc.dir/src/SiddhartaEnergyDeposition.cpp.s
.PHONY : src/SiddhartaEnergyDeposition.cpp.s

src/SiddhartaEventAction.o: src/SiddhartaEventAction.cpp.o
.PHONY : src/SiddhartaEventAction.o

# target to build an object file
src/SiddhartaEventAction.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sidd_mc.dir/build.make CMakeFiles/sidd_mc.dir/src/SiddhartaEventAction.cpp.o
.PHONY : src/SiddhartaEventAction.cpp.o

src/SiddhartaEventAction.i: src/SiddhartaEventAction.cpp.i
.PHONY : src/SiddhartaEventAction.i

# target to preprocess a source file
src/SiddhartaEventAction.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sidd_mc.dir/build.make CMakeFiles/sidd_mc.dir/src/SiddhartaEventAction.cpp.i
.PHONY : src/SiddhartaEventAction.cpp.i

src/SiddhartaEventAction.s: src/SiddhartaEventAction.cpp.s
.PHONY : src/SiddhartaEventAction.s

# target to generate assembly for a file
src/SiddhartaEventAction.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sidd_mc.dir/build.make CMakeFiles/sidd_mc.dir/src/SiddhartaEventAction.cpp.s
.PHONY : src/SiddhartaEventAction.cpp.s

src/SiddhartaGhostSD.o: src/SiddhartaGhostSD.cpp.o
.PHONY : src/SiddhartaGhostSD.o

# target to build an object file
src/SiddhartaGhostSD.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sidd_mc.dir/build.make CMakeFiles/sidd_mc.dir/src/SiddhartaGhostSD.cpp.o
.PHONY : src/SiddhartaGhostSD.cpp.o

src/SiddhartaGhostSD.i: src/SiddhartaGhostSD.cpp.i
.PHONY : src/SiddhartaGhostSD.i

# target to preprocess a source file
src/SiddhartaGhostSD.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sidd_mc.dir/build.make CMakeFiles/sidd_mc.dir/src/SiddhartaGhostSD.cpp.i
.PHONY : src/SiddhartaGhostSD.cpp.i

src/SiddhartaGhostSD.s: src/SiddhartaGhostSD.cpp.s
.PHONY : src/SiddhartaGhostSD.s

# target to generate assembly for a file
src/SiddhartaGhostSD.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sidd_mc.dir/build.make CMakeFiles/sidd_mc.dir/src/SiddhartaGhostSD.cpp.s
.PHONY : src/SiddhartaGhostSD.cpp.s

src/SiddhartaHisto.o: src/SiddhartaHisto.cpp.o
.PHONY : src/SiddhartaHisto.o

# target to build an object file
src/SiddhartaHisto.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sidd_mc.dir/build.make CMakeFiles/sidd_mc.dir/src/SiddhartaHisto.cpp.o
.PHONY : src/SiddhartaHisto.cpp.o

src/SiddhartaHisto.i: src/SiddhartaHisto.cpp.i
.PHONY : src/SiddhartaHisto.i

# target to preprocess a source file
src/SiddhartaHisto.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sidd_mc.dir/build.make CMakeFiles/sidd_mc.dir/src/SiddhartaHisto.cpp.i
.PHONY : src/SiddhartaHisto.cpp.i

src/SiddhartaHisto.s: src/SiddhartaHisto.cpp.s
.PHONY : src/SiddhartaHisto.s

# target to generate assembly for a file
src/SiddhartaHisto.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sidd_mc.dir/build.make CMakeFiles/sidd_mc.dir/src/SiddhartaHisto.cpp.s
.PHONY : src/SiddhartaHisto.cpp.s

src/SiddhartaKPlusSD.o: src/SiddhartaKPlusSD.cpp.o
.PHONY : src/SiddhartaKPlusSD.o

# target to build an object file
src/SiddhartaKPlusSD.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sidd_mc.dir/build.make CMakeFiles/sidd_mc.dir/src/SiddhartaKPlusSD.cpp.o
.PHONY : src/SiddhartaKPlusSD.cpp.o

src/SiddhartaKPlusSD.i: src/SiddhartaKPlusSD.cpp.i
.PHONY : src/SiddhartaKPlusSD.i

# target to preprocess a source file
src/SiddhartaKPlusSD.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sidd_mc.dir/build.make CMakeFiles/sidd_mc.dir/src/SiddhartaKPlusSD.cpp.i
.PHONY : src/SiddhartaKPlusSD.cpp.i

src/SiddhartaKPlusSD.s: src/SiddhartaKPlusSD.cpp.s
.PHONY : src/SiddhartaKPlusSD.s

# target to generate assembly for a file
src/SiddhartaKPlusSD.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sidd_mc.dir/build.make CMakeFiles/sidd_mc.dir/src/SiddhartaKPlusSD.cpp.s
.PHONY : src/SiddhartaKPlusSD.cpp.s

src/SiddhartaKaonDetectorBottomSD.o: src/SiddhartaKaonDetectorBottomSD.cpp.o
.PHONY : src/SiddhartaKaonDetectorBottomSD.o

# target to build an object file
src/SiddhartaKaonDetectorBottomSD.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sidd_mc.dir/build.make CMakeFiles/sidd_mc.dir/src/SiddhartaKaonDetectorBottomSD.cpp.o
.PHONY : src/SiddhartaKaonDetectorBottomSD.cpp.o

src/SiddhartaKaonDetectorBottomSD.i: src/SiddhartaKaonDetectorBottomSD.cpp.i
.PHONY : src/SiddhartaKaonDetectorBottomSD.i

# target to preprocess a source file
src/SiddhartaKaonDetectorBottomSD.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sidd_mc.dir/build.make CMakeFiles/sidd_mc.dir/src/SiddhartaKaonDetectorBottomSD.cpp.i
.PHONY : src/SiddhartaKaonDetectorBottomSD.cpp.i

src/SiddhartaKaonDetectorBottomSD.s: src/SiddhartaKaonDetectorBottomSD.cpp.s
.PHONY : src/SiddhartaKaonDetectorBottomSD.s

# target to generate assembly for a file
src/SiddhartaKaonDetectorBottomSD.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sidd_mc.dir/build.make CMakeFiles/sidd_mc.dir/src/SiddhartaKaonDetectorBottomSD.cpp.s
.PHONY : src/SiddhartaKaonDetectorBottomSD.cpp.s

src/SiddhartaKaonDetectorTopSD.o: src/SiddhartaKaonDetectorTopSD.cpp.o
.PHONY : src/SiddhartaKaonDetectorTopSD.o

# target to build an object file
src/SiddhartaKaonDetectorTopSD.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sidd_mc.dir/build.make CMakeFiles/sidd_mc.dir/src/SiddhartaKaonDetectorTopSD.cpp.o
.PHONY : src/SiddhartaKaonDetectorTopSD.cpp.o

src/SiddhartaKaonDetectorTopSD.i: src/SiddhartaKaonDetectorTopSD.cpp.i
.PHONY : src/SiddhartaKaonDetectorTopSD.i

# target to preprocess a source file
src/SiddhartaKaonDetectorTopSD.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sidd_mc.dir/build.make CMakeFiles/sidd_mc.dir/src/SiddhartaKaonDetectorTopSD.cpp.i
.PHONY : src/SiddhartaKaonDetectorTopSD.cpp.i

src/SiddhartaKaonDetectorTopSD.s: src/SiddhartaKaonDetectorTopSD.cpp.s
.PHONY : src/SiddhartaKaonDetectorTopSD.s

# target to generate assembly for a file
src/SiddhartaKaonDetectorTopSD.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sidd_mc.dir/build.make CMakeFiles/sidd_mc.dir/src/SiddhartaKaonDetectorTopSD.cpp.s
.PHONY : src/SiddhartaKaonDetectorTopSD.cpp.s

src/SiddhartaLumiDetectorAntiboostSD.o: src/SiddhartaLumiDetectorAntiboostSD.cpp.o
.PHONY : src/SiddhartaLumiDetectorAntiboostSD.o

# target to build an object file
src/SiddhartaLumiDetectorAntiboostSD.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sidd_mc.dir/build.make CMakeFiles/sidd_mc.dir/src/SiddhartaLumiDetectorAntiboostSD.cpp.o
.PHONY : src/SiddhartaLumiDetectorAntiboostSD.cpp.o

src/SiddhartaLumiDetectorAntiboostSD.i: src/SiddhartaLumiDetectorAntiboostSD.cpp.i
.PHONY : src/SiddhartaLumiDetectorAntiboostSD.i

# target to preprocess a source file
src/SiddhartaLumiDetectorAntiboostSD.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sidd_mc.dir/build.make CMakeFiles/sidd_mc.dir/src/SiddhartaLumiDetectorAntiboostSD.cpp.i
.PHONY : src/SiddhartaLumiDetectorAntiboostSD.cpp.i

src/SiddhartaLumiDetectorAntiboostSD.s: src/SiddhartaLumiDetectorAntiboostSD.cpp.s
.PHONY : src/SiddhartaLumiDetectorAntiboostSD.s

# target to generate assembly for a file
src/SiddhartaLumiDetectorAntiboostSD.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sidd_mc.dir/build.make CMakeFiles/sidd_mc.dir/src/SiddhartaLumiDetectorAntiboostSD.cpp.s
.PHONY : src/SiddhartaLumiDetectorAntiboostSD.cpp.s

src/SiddhartaLumiDetectorBoostSD.o: src/SiddhartaLumiDetectorBoostSD.cpp.o
.PHONY : src/SiddhartaLumiDetectorBoostSD.o

# target to build an object file
src/SiddhartaLumiDetectorBoostSD.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sidd_mc.dir/build.make CMakeFiles/sidd_mc.dir/src/SiddhartaLumiDetectorBoostSD.cpp.o
.PHONY : src/SiddhartaLumiDetectorBoostSD.cpp.o

src/SiddhartaLumiDetectorBoostSD.i: src/SiddhartaLumiDetectorBoostSD.cpp.i
.PHONY : src/SiddhartaLumiDetectorBoostSD.i

# target to preprocess a source file
src/SiddhartaLumiDetectorBoostSD.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sidd_mc.dir/build.make CMakeFiles/sidd_mc.dir/src/SiddhartaLumiDetectorBoostSD.cpp.i
.PHONY : src/SiddhartaLumiDetectorBoostSD.cpp.i

src/SiddhartaLumiDetectorBoostSD.s: src/SiddhartaLumiDetectorBoostSD.cpp.s
.PHONY : src/SiddhartaLumiDetectorBoostSD.s

# target to generate assembly for a file
src/SiddhartaLumiDetectorBoostSD.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sidd_mc.dir/build.make CMakeFiles/sidd_mc.dir/src/SiddhartaLumiDetectorBoostSD.cpp.s
.PHONY : src/SiddhartaLumiDetectorBoostSD.cpp.s

src/SiddhartaMagneticField.o: src/SiddhartaMagneticField.cpp.o
.PHONY : src/SiddhartaMagneticField.o

# target to build an object file
src/SiddhartaMagneticField.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sidd_mc.dir/build.make CMakeFiles/sidd_mc.dir/src/SiddhartaMagneticField.cpp.o
.PHONY : src/SiddhartaMagneticField.cpp.o

src/SiddhartaMagneticField.i: src/SiddhartaMagneticField.cpp.i
.PHONY : src/SiddhartaMagneticField.i

# target to preprocess a source file
src/SiddhartaMagneticField.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sidd_mc.dir/build.make CMakeFiles/sidd_mc.dir/src/SiddhartaMagneticField.cpp.i
.PHONY : src/SiddhartaMagneticField.cpp.i

src/SiddhartaMagneticField.s: src/SiddhartaMagneticField.cpp.s
.PHONY : src/SiddhartaMagneticField.s

# target to generate assembly for a file
src/SiddhartaMagneticField.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sidd_mc.dir/build.make CMakeFiles/sidd_mc.dir/src/SiddhartaMagneticField.cpp.s
.PHONY : src/SiddhartaMagneticField.cpp.s

src/SiddhartaParticleGun.o: src/SiddhartaParticleGun.cpp.o
.PHONY : src/SiddhartaParticleGun.o

# target to build an object file
src/SiddhartaParticleGun.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sidd_mc.dir/build.make CMakeFiles/sidd_mc.dir/src/SiddhartaParticleGun.cpp.o
.PHONY : src/SiddhartaParticleGun.cpp.o

src/SiddhartaParticleGun.i: src/SiddhartaParticleGun.cpp.i
.PHONY : src/SiddhartaParticleGun.i

# target to preprocess a source file
src/SiddhartaParticleGun.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sidd_mc.dir/build.make CMakeFiles/sidd_mc.dir/src/SiddhartaParticleGun.cpp.i
.PHONY : src/SiddhartaParticleGun.cpp.i

src/SiddhartaParticleGun.s: src/SiddhartaParticleGun.cpp.s
.PHONY : src/SiddhartaParticleGun.s

# target to generate assembly for a file
src/SiddhartaParticleGun.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sidd_mc.dir/build.make CMakeFiles/sidd_mc.dir/src/SiddhartaParticleGun.cpp.s
.PHONY : src/SiddhartaParticleGun.cpp.s

src/SiddhartaPhysicsList.o: src/SiddhartaPhysicsList.cpp.o
.PHONY : src/SiddhartaPhysicsList.o

# target to build an object file
src/SiddhartaPhysicsList.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sidd_mc.dir/build.make CMakeFiles/sidd_mc.dir/src/SiddhartaPhysicsList.cpp.o
.PHONY : src/SiddhartaPhysicsList.cpp.o

src/SiddhartaPhysicsList.i: src/SiddhartaPhysicsList.cpp.i
.PHONY : src/SiddhartaPhysicsList.i

# target to preprocess a source file
src/SiddhartaPhysicsList.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sidd_mc.dir/build.make CMakeFiles/sidd_mc.dir/src/SiddhartaPhysicsList.cpp.i
.PHONY : src/SiddhartaPhysicsList.cpp.i

src/SiddhartaPhysicsList.s: src/SiddhartaPhysicsList.cpp.s
.PHONY : src/SiddhartaPhysicsList.s

# target to generate assembly for a file
src/SiddhartaPhysicsList.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sidd_mc.dir/build.make CMakeFiles/sidd_mc.dir/src/SiddhartaPhysicsList.cpp.s
.PHONY : src/SiddhartaPhysicsList.cpp.s

src/SiddhartaPrimaryGeneratorAction.o: src/SiddhartaPrimaryGeneratorAction.cpp.o
.PHONY : src/SiddhartaPrimaryGeneratorAction.o

# target to build an object file
src/SiddhartaPrimaryGeneratorAction.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sidd_mc.dir/build.make CMakeFiles/sidd_mc.dir/src/SiddhartaPrimaryGeneratorAction.cpp.o
.PHONY : src/SiddhartaPrimaryGeneratorAction.cpp.o

src/SiddhartaPrimaryGeneratorAction.i: src/SiddhartaPrimaryGeneratorAction.cpp.i
.PHONY : src/SiddhartaPrimaryGeneratorAction.i

# target to preprocess a source file
src/SiddhartaPrimaryGeneratorAction.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sidd_mc.dir/build.make CMakeFiles/sidd_mc.dir/src/SiddhartaPrimaryGeneratorAction.cpp.i
.PHONY : src/SiddhartaPrimaryGeneratorAction.cpp.i

src/SiddhartaPrimaryGeneratorAction.s: src/SiddhartaPrimaryGeneratorAction.cpp.s
.PHONY : src/SiddhartaPrimaryGeneratorAction.s

# target to generate assembly for a file
src/SiddhartaPrimaryGeneratorAction.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sidd_mc.dir/build.make CMakeFiles/sidd_mc.dir/src/SiddhartaPrimaryGeneratorAction.cpp.s
.PHONY : src/SiddhartaPrimaryGeneratorAction.cpp.s

src/SiddhartaRunAction.o: src/SiddhartaRunAction.cpp.o
.PHONY : src/SiddhartaRunAction.o

# target to build an object file
src/SiddhartaRunAction.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sidd_mc.dir/build.make CMakeFiles/sidd_mc.dir/src/SiddhartaRunAction.cpp.o
.PHONY : src/SiddhartaRunAction.cpp.o

src/SiddhartaRunAction.i: src/SiddhartaRunAction.cpp.i
.PHONY : src/SiddhartaRunAction.i

# target to preprocess a source file
src/SiddhartaRunAction.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sidd_mc.dir/build.make CMakeFiles/sidd_mc.dir/src/SiddhartaRunAction.cpp.i
.PHONY : src/SiddhartaRunAction.cpp.i

src/SiddhartaRunAction.s: src/SiddhartaRunAction.cpp.s
.PHONY : src/SiddhartaRunAction.s

# target to generate assembly for a file
src/SiddhartaRunAction.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sidd_mc.dir/build.make CMakeFiles/sidd_mc.dir/src/SiddhartaRunAction.cpp.s
.PHONY : src/SiddhartaRunAction.cpp.s

src/SiddhartaScintAntiSD.o: src/SiddhartaScintAntiSD.cpp.o
.PHONY : src/SiddhartaScintAntiSD.o

# target to build an object file
src/SiddhartaScintAntiSD.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sidd_mc.dir/build.make CMakeFiles/sidd_mc.dir/src/SiddhartaScintAntiSD.cpp.o
.PHONY : src/SiddhartaScintAntiSD.cpp.o

src/SiddhartaScintAntiSD.i: src/SiddhartaScintAntiSD.cpp.i
.PHONY : src/SiddhartaScintAntiSD.i

# target to preprocess a source file
src/SiddhartaScintAntiSD.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sidd_mc.dir/build.make CMakeFiles/sidd_mc.dir/src/SiddhartaScintAntiSD.cpp.i
.PHONY : src/SiddhartaScintAntiSD.cpp.i

src/SiddhartaScintAntiSD.s: src/SiddhartaScintAntiSD.cpp.s
.PHONY : src/SiddhartaScintAntiSD.s

# target to generate assembly for a file
src/SiddhartaScintAntiSD.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sidd_mc.dir/build.make CMakeFiles/sidd_mc.dir/src/SiddhartaScintAntiSD.cpp.s
.PHONY : src/SiddhartaScintAntiSD.cpp.s

src/SiddhartaSteppingAction.o: src/SiddhartaSteppingAction.cpp.o
.PHONY : src/SiddhartaSteppingAction.o

# target to build an object file
src/SiddhartaSteppingAction.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sidd_mc.dir/build.make CMakeFiles/sidd_mc.dir/src/SiddhartaSteppingAction.cpp.o
.PHONY : src/SiddhartaSteppingAction.cpp.o

src/SiddhartaSteppingAction.i: src/SiddhartaSteppingAction.cpp.i
.PHONY : src/SiddhartaSteppingAction.i

# target to preprocess a source file
src/SiddhartaSteppingAction.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sidd_mc.dir/build.make CMakeFiles/sidd_mc.dir/src/SiddhartaSteppingAction.cpp.i
.PHONY : src/SiddhartaSteppingAction.cpp.i

src/SiddhartaSteppingAction.s: src/SiddhartaSteppingAction.cpp.s
.PHONY : src/SiddhartaSteppingAction.s

# target to generate assembly for a file
src/SiddhartaSteppingAction.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sidd_mc.dir/build.make CMakeFiles/sidd_mc.dir/src/SiddhartaSteppingAction.cpp.s
.PHONY : src/SiddhartaSteppingAction.cpp.s

src/SiddhartaSteppingVerbose.o: src/SiddhartaSteppingVerbose.cpp.o
.PHONY : src/SiddhartaSteppingVerbose.o

# target to build an object file
src/SiddhartaSteppingVerbose.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sidd_mc.dir/build.make CMakeFiles/sidd_mc.dir/src/SiddhartaSteppingVerbose.cpp.o
.PHONY : src/SiddhartaSteppingVerbose.cpp.o

src/SiddhartaSteppingVerbose.i: src/SiddhartaSteppingVerbose.cpp.i
.PHONY : src/SiddhartaSteppingVerbose.i

# target to preprocess a source file
src/SiddhartaSteppingVerbose.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sidd_mc.dir/build.make CMakeFiles/sidd_mc.dir/src/SiddhartaSteppingVerbose.cpp.i
.PHONY : src/SiddhartaSteppingVerbose.cpp.i

src/SiddhartaSteppingVerbose.s: src/SiddhartaSteppingVerbose.cpp.s
.PHONY : src/SiddhartaSteppingVerbose.s

# target to generate assembly for a file
src/SiddhartaSteppingVerbose.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sidd_mc.dir/build.make CMakeFiles/sidd_mc.dir/src/SiddhartaSteppingVerbose.cpp.s
.PHONY : src/SiddhartaSteppingVerbose.cpp.s

src/SiddhartaTrackerHit.o: src/SiddhartaTrackerHit.cpp.o
.PHONY : src/SiddhartaTrackerHit.o

# target to build an object file
src/SiddhartaTrackerHit.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sidd_mc.dir/build.make CMakeFiles/sidd_mc.dir/src/SiddhartaTrackerHit.cpp.o
.PHONY : src/SiddhartaTrackerHit.cpp.o

src/SiddhartaTrackerHit.i: src/SiddhartaTrackerHit.cpp.i
.PHONY : src/SiddhartaTrackerHit.i

# target to preprocess a source file
src/SiddhartaTrackerHit.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sidd_mc.dir/build.make CMakeFiles/sidd_mc.dir/src/SiddhartaTrackerHit.cpp.i
.PHONY : src/SiddhartaTrackerHit.cpp.i

src/SiddhartaTrackerHit.s: src/SiddhartaTrackerHit.cpp.s
.PHONY : src/SiddhartaTrackerHit.s

# target to generate assembly for a file
src/SiddhartaTrackerHit.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sidd_mc.dir/build.make CMakeFiles/sidd_mc.dir/src/SiddhartaTrackerHit.cpp.s
.PHONY : src/SiddhartaTrackerHit.cpp.s

src/SiddhartaTrackerSD.o: src/SiddhartaTrackerSD.cpp.o
.PHONY : src/SiddhartaTrackerSD.o

# target to build an object file
src/SiddhartaTrackerSD.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sidd_mc.dir/build.make CMakeFiles/sidd_mc.dir/src/SiddhartaTrackerSD.cpp.o
.PHONY : src/SiddhartaTrackerSD.cpp.o

src/SiddhartaTrackerSD.i: src/SiddhartaTrackerSD.cpp.i
.PHONY : src/SiddhartaTrackerSD.i

# target to preprocess a source file
src/SiddhartaTrackerSD.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sidd_mc.dir/build.make CMakeFiles/sidd_mc.dir/src/SiddhartaTrackerSD.cpp.i
.PHONY : src/SiddhartaTrackerSD.cpp.i

src/SiddhartaTrackerSD.s: src/SiddhartaTrackerSD.cpp.s
.PHONY : src/SiddhartaTrackerSD.s

# target to generate assembly for a file
src/SiddhartaTrackerSD.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sidd_mc.dir/build.make CMakeFiles/sidd_mc.dir/src/SiddhartaTrackerSD.cpp.s
.PHONY : src/SiddhartaTrackerSD.cpp.s

src/SiddhartaTrackingAction.o: src/SiddhartaTrackingAction.cpp.o
.PHONY : src/SiddhartaTrackingAction.o

# target to build an object file
src/SiddhartaTrackingAction.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sidd_mc.dir/build.make CMakeFiles/sidd_mc.dir/src/SiddhartaTrackingAction.cpp.o
.PHONY : src/SiddhartaTrackingAction.cpp.o

src/SiddhartaTrackingAction.i: src/SiddhartaTrackingAction.cpp.i
.PHONY : src/SiddhartaTrackingAction.i

# target to preprocess a source file
src/SiddhartaTrackingAction.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sidd_mc.dir/build.make CMakeFiles/sidd_mc.dir/src/SiddhartaTrackingAction.cpp.i
.PHONY : src/SiddhartaTrackingAction.cpp.i

src/SiddhartaTrackingAction.s: src/SiddhartaTrackingAction.cpp.s
.PHONY : src/SiddhartaTrackingAction.s

# target to generate assembly for a file
src/SiddhartaTrackingAction.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sidd_mc.dir/build.make CMakeFiles/sidd_mc.dir/src/SiddhartaTrackingAction.cpp.s
.PHONY : src/SiddhartaTrackingAction.cpp.s

src/SinsqDecayChannel.o: src/SinsqDecayChannel.cpp.o
.PHONY : src/SinsqDecayChannel.o

# target to build an object file
src/SinsqDecayChannel.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sidd_mc.dir/build.make CMakeFiles/sidd_mc.dir/src/SinsqDecayChannel.cpp.o
.PHONY : src/SinsqDecayChannel.cpp.o

src/SinsqDecayChannel.i: src/SinsqDecayChannel.cpp.i
.PHONY : src/SinsqDecayChannel.i

# target to preprocess a source file
src/SinsqDecayChannel.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sidd_mc.dir/build.make CMakeFiles/sidd_mc.dir/src/SinsqDecayChannel.cpp.i
.PHONY : src/SinsqDecayChannel.cpp.i

src/SinsqDecayChannel.s: src/SinsqDecayChannel.cpp.s
.PHONY : src/SinsqDecayChannel.s

# target to generate assembly for a file
src/SinsqDecayChannel.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sidd_mc.dir/build.make CMakeFiles/sidd_mc.dir/src/SinsqDecayChannel.cpp.s
.PHONY : src/SinsqDecayChannel.cpp.s

src/SpecialCuts.o: src/SpecialCuts.cpp.o
.PHONY : src/SpecialCuts.o

# target to build an object file
src/SpecialCuts.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sidd_mc.dir/build.make CMakeFiles/sidd_mc.dir/src/SpecialCuts.cpp.o
.PHONY : src/SpecialCuts.cpp.o

src/SpecialCuts.i: src/SpecialCuts.cpp.i
.PHONY : src/SpecialCuts.i

# target to preprocess a source file
src/SpecialCuts.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sidd_mc.dir/build.make CMakeFiles/sidd_mc.dir/src/SpecialCuts.cpp.i
.PHONY : src/SpecialCuts.cpp.i

src/SpecialCuts.s: src/SpecialCuts.cpp.s
.PHONY : src/SpecialCuts.s

# target to generate assembly for a file
src/SpecialCuts.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sidd_mc.dir/build.make CMakeFiles/sidd_mc.dir/src/SpecialCuts.cpp.s
.PHONY : src/SpecialCuts.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... sidd_mc"
	@echo "... Siddharta.o"
	@echo "... Siddharta.i"
	@echo "... Siddharta.s"
	@echo "... src/G4KaonMinusAbsorptionAtRest.o"
	@echo "... src/G4KaonMinusAbsorptionAtRest.i"
	@echo "... src/G4KaonMinusAbsorptionAtRest.s"
	@echo "... src/G4ShortLivedConstructor.o"
	@echo "... src/G4ShortLivedConstructor.i"
	@echo "... src/G4ShortLivedConstructor.s"
	@echo "... src/PhiMassFunction.o"
	@echo "... src/PhiMassFunction.i"
	@echo "... src/PhiMassFunction.s"
	@echo "... src/SiddhartaAnalysisManager.o"
	@echo "... src/SiddhartaAnalysisManager.i"
	@echo "... src/SiddhartaAnalysisManager.s"
	@echo "... src/SiddhartaAnti1SD.o"
	@echo "... src/SiddhartaAnti1SD.i"
	@echo "... src/SiddhartaAnti1SD.s"
	@echo "... src/SiddhartaAnti2SD.o"
	@echo "... src/SiddhartaAnti2SD.i"
	@echo "... src/SiddhartaAnti2SD.s"
	@echo "... src/SiddhartaAnti3SD.o"
	@echo "... src/SiddhartaAnti3SD.i"
	@echo "... src/SiddhartaAnti3SD.s"
	@echo "... src/SiddhartaAnti4SD.o"
	@echo "... src/SiddhartaAnti4SD.i"
	@echo "... src/SiddhartaAnti4SD.s"
	@echo "... src/SiddhartaAnti5SD.o"
	@echo "... src/SiddhartaAnti5SD.i"
	@echo "... src/SiddhartaAnti5SD.s"
	@echo "... src/SiddhartaCard.o"
	@echo "... src/SiddhartaCard.i"
	@echo "... src/SiddhartaCard.s"
	@echo "... src/SiddhartaDetectorConstruction.o"
	@echo "... src/SiddhartaDetectorConstruction.i"
	@echo "... src/SiddhartaDetectorConstruction.s"
	@echo "... src/SiddhartaDetectorMessenger.o"
	@echo "... src/SiddhartaDetectorMessenger.i"
	@echo "... src/SiddhartaDetectorMessenger.s"
	@echo "... src/SiddhartaEnergyDeposition.o"
	@echo "... src/SiddhartaEnergyDeposition.i"
	@echo "... src/SiddhartaEnergyDeposition.s"
	@echo "... src/SiddhartaEventAction.o"
	@echo "... src/SiddhartaEventAction.i"
	@echo "... src/SiddhartaEventAction.s"
	@echo "... src/SiddhartaGhostSD.o"
	@echo "... src/SiddhartaGhostSD.i"
	@echo "... src/SiddhartaGhostSD.s"
	@echo "... src/SiddhartaHisto.o"
	@echo "... src/SiddhartaHisto.i"
	@echo "... src/SiddhartaHisto.s"
	@echo "... src/SiddhartaKPlusSD.o"
	@echo "... src/SiddhartaKPlusSD.i"
	@echo "... src/SiddhartaKPlusSD.s"
	@echo "... src/SiddhartaKaonDetectorBottomSD.o"
	@echo "... src/SiddhartaKaonDetectorBottomSD.i"
	@echo "... src/SiddhartaKaonDetectorBottomSD.s"
	@echo "... src/SiddhartaKaonDetectorTopSD.o"
	@echo "... src/SiddhartaKaonDetectorTopSD.i"
	@echo "... src/SiddhartaKaonDetectorTopSD.s"
	@echo "... src/SiddhartaLumiDetectorAntiboostSD.o"
	@echo "... src/SiddhartaLumiDetectorAntiboostSD.i"
	@echo "... src/SiddhartaLumiDetectorAntiboostSD.s"
	@echo "... src/SiddhartaLumiDetectorBoostSD.o"
	@echo "... src/SiddhartaLumiDetectorBoostSD.i"
	@echo "... src/SiddhartaLumiDetectorBoostSD.s"
	@echo "... src/SiddhartaMagneticField.o"
	@echo "... src/SiddhartaMagneticField.i"
	@echo "... src/SiddhartaMagneticField.s"
	@echo "... src/SiddhartaParticleGun.o"
	@echo "... src/SiddhartaParticleGun.i"
	@echo "... src/SiddhartaParticleGun.s"
	@echo "... src/SiddhartaPhysicsList.o"
	@echo "... src/SiddhartaPhysicsList.i"
	@echo "... src/SiddhartaPhysicsList.s"
	@echo "... src/SiddhartaPrimaryGeneratorAction.o"
	@echo "... src/SiddhartaPrimaryGeneratorAction.i"
	@echo "... src/SiddhartaPrimaryGeneratorAction.s"
	@echo "... src/SiddhartaRunAction.o"
	@echo "... src/SiddhartaRunAction.i"
	@echo "... src/SiddhartaRunAction.s"
	@echo "... src/SiddhartaScintAntiSD.o"
	@echo "... src/SiddhartaScintAntiSD.i"
	@echo "... src/SiddhartaScintAntiSD.s"
	@echo "... src/SiddhartaSteppingAction.o"
	@echo "... src/SiddhartaSteppingAction.i"
	@echo "... src/SiddhartaSteppingAction.s"
	@echo "... src/SiddhartaSteppingVerbose.o"
	@echo "... src/SiddhartaSteppingVerbose.i"
	@echo "... src/SiddhartaSteppingVerbose.s"
	@echo "... src/SiddhartaTrackerHit.o"
	@echo "... src/SiddhartaTrackerHit.i"
	@echo "... src/SiddhartaTrackerHit.s"
	@echo "... src/SiddhartaTrackerSD.o"
	@echo "... src/SiddhartaTrackerSD.i"
	@echo "... src/SiddhartaTrackerSD.s"
	@echo "... src/SiddhartaTrackingAction.o"
	@echo "... src/SiddhartaTrackingAction.i"
	@echo "... src/SiddhartaTrackingAction.s"
	@echo "... src/SinsqDecayChannel.o"
	@echo "... src/SinsqDecayChannel.i"
	@echo "... src/SinsqDecayChannel.s"
	@echo "... src/SpecialCuts.o"
	@echo "... src/SpecialCuts.i"
	@echo "... src/SpecialCuts.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

